services:
  webserver:
    image: docker.io/caddy:2.9
    volumes:
      - "$PWD/caddy:/etc/caddy"
      - "$PWD/uploads:/app/uploads"
      - "$PWD/productionfiles:/app/static"
    ports:
      - "8000:8000"
  app:
    container_name: splootwyze
    build: .
    environment:
      ENV: dev
    volumes:
      - "$PWD/secret_key.txt:/app/secret_key.txt"
      - "$PWD/data/db.sqlite3:/app/data/db.sqlite3"
      - "$PWD/uploads:/app/uploads"
