# Generated by Django 5.0.6 on 2024-07-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
    ]
