# Generated by Django 5.0.6 on 2024-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_user_created_at_user_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
