# Generated by Django 5.1.6 on 2025-10-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(null=True, upload_to='receipts'),
        ),
    ]
