# Generated by Django 5.2.7 on 2025-10-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_receipt_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
