# Generated by Django 5.2.7 on 2025-10-11 18:30

from django.contrib.auth.models import Group
from django.db import migrations, models


def migrate_to_default_group(apps, schema_editor):
    Expenses = apps.get_model("expenses", "Expense")
    Group = apps.get_model("auth", "Group")
    default_group, created = Group.objects.get_or_create(name="Default")
    for expense in Expenses.objects.all():
        expense.group = default_group
        expense.save()


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey("auth.Group", on_delete=models.CASCADE, null=True),
        ),
        migrations.RunPython(migrate_to_default_group),
        migrations.AlterField(
            model_name="expense",
            name="group",
            field=models.ForeignKey("auth.Group", on_delete=models.CASCADE, null=False),
        ),
    ]
