# Usage:
#   ansible-playbook -i 'example.com,' deployment/vps.yml -u USERNAME --ask-become-pass --vault-password-file deployment/vault_pass.txt
---
- hosts: all
  vars:
    app_user: splootwyze
    app_group: "{{ app_user }}"
    app_home: "/home/{{ app_user }}"
    app_repo: "{{ app_home }}/splootwyze.git"
    app_root: "{{ app_home }}/applicationroot"
    backup_root: "/mnt/media-and-backups/{{ app_user }}/backups"
    db_path: "/var/lib/{{ app_user }}/db.sqlite3"
    media_root: "/mnt/media-and-backups/{{ app_user }}/media"
    static_root: "/srv/{{ app_user }}/staticfiles"

    packages:
      - ffmpeg
      - git
      - python3-pip
      - python3.13-venv
      - rsync
      - sqlite3
      - virtualenv

    service_dirs:
      - /etc/systemd/system/{{ app_user }}.service.d/
      - /etc/systemd/system/caddy.service.d/

    app_dirs:
      - "{{ backup_root }}"
      - "{{ media_root }}"
      - "{{ static_root }}"

    service_env:
      SPLOOTWYZE_ALLOWED_HOSTS: "splootwyze.ajcajc.com"
      SPLOOTWYZE_MEDIA_ROOT: "{{ media_root }}"
      SPLOOTWYZE_SQLITE_PATH: "{{ db_path }}"
      SPLOOTWYZE_STATIC_ROOT: "{{ static_root }}"

  tasks:
    - name: Install required packages
      become: true
      apt:
        update_cache: true
        name: "{{ packages }}"

    - name: Ensure application user exists
      become: true
      user:
        name: "{{ app_user }}"
        create_home: true
        shell: /bin/bash

    - name: Add current user to app group
      become: true
      user:
        name: "{{ ansible_user_id }}"
        groups: "{{ app_group }}"
        append: true

    - name: Add local SSH key for {{ app_user }}
      become: true
      authorized_key:
        user: "{{ app_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Configure global git defaults
      remote_user: "{{ app_user }}"
      copy:
        dest: "{{ app_home }}/.gitconfig"
        content: |
          [init]
          defaultBranch = main

    - name: Initialize bare repo if missing
      remote_user: "{{ app_user }}"
      command: git init --bare "{{ app_repo }}"
      args:
        creates: "{{ app_repo }}/HEAD"

    - name: Push local repo
      delegate_to: localhost
      command: git push www main

    - name: Clone or update working repo
      remote_user: "{{ app_user }}"
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_root }}"
        clone: true
        update: true
      notify: restart splootwyze

    - name: Install Python dependencies
      remote_user: "{{ app_user }}"
      pip:
        requirements: "{{ app_root }}/requirements.txt"
        virtualenv: "{{ app_root }}/.venv"

    - name: Create systemd drop-in directories
      become: true
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
      loop: "{{ service_dirs }}"

    - name: Ensure web directories exist and owned by {{ app_user }}
      become: true
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0775"
      loop: "{{ app_dirs }}"

    - name: Install systemd unit files
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "/etc/systemd/system/{{ item.dest }}"
      loop:
        - { src: "splootwyze.service", dest: "splootwyze.service" }
        - { src: "splootwyze.socket", dest: "splootwyze.socket" }
      notify: restart splootwyze

    - name: Deploy env configuration to services
      become: true
      copy:
        content: |
          [Service]
          {% for key, value in service_env.items() %}
          Environment={{ key }}="{{ value }}"
          {% endfor %}
        dest: "{{ item }}/50-splootwyze-env.conf"
      loop:
        - /etc/systemd/system/splootwyze.service.d/
        - /etc/systemd/system/caddy.service.d/
      notify:
        - reload caddy
        - restart splootwyze

    - name: Optionally configure systemd-creds secret key
      when: setup_creds | default(false)
      block:
        - name: Initialize systemd-creds
          become: true
          command: systemd-creds setup

        # encrypted with the following command
        # `ansible-vault encrypt_string --vault-password-file deployment/vault_pass.txt`
        - name: Encrypt secret key credential
          become: true
          community.general.systemd_creds_encrypt:
            name: "{{ app_user }}-secret-key"
            secret: "{{ secret_key }}"
            pretty: true
          register: secret_key
          vars:
            secret_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              65396665653165646437323139313533666332636166643336346338303234646435386263323561
              3462663734323636303236363963663130663935383564630a383339373664373133646565613162
              39316266333066316333323362336664303734343230396265326464316239643961396562376462
              3664613661666262610a396136663831366533633733333035616238616438323636336138626432
              63333737373062373130653937353565353263383361366662646433333464326636393033393661
              37653036313934363466343830393737363531363261653066663862383661363431396232663666
              613039653664666330333065353162623234

        - name: Write systemd drop-in with secret key env
          become: true
          copy:
            dest: "/etc/systemd/system/{{ app_user }}.service.d/51-secret-key.conf"
            content: |
              [Service]
              {{ secret_key.value }}
              Environment=SPLOOTWYZE_SECRET_KEY_FILE=%d/{{ app_user }}-secret-key
          notify: restart splootwyze

    - name: Copy Caddyfile
      become: true
      copy:
        src: Caddyfile.prod
        dest: /etc/caddy/sites-available/splootwyze.ajcajc.com
      notify: reload caddy

    - name: Enable splootwyze Caddyfile
      become: true
      file:
        src: /etc/caddy/sites-available/splootwyze.ajcajc.com
        state: link
        dest: /etc/caddy/sites-enabled/splootwyze.ajcajc.com
      notify: reload caddy

    - name: Install backup script
      become: true
      copy:
        dest: /usr/local/bin/backup-{{ app_user }}.sh
        mode: "0777"
        content: |
          #!/bin/bash
          DATE=$(date +"%Y-%m-%d_%H-%M-%S")
          BACKUP_FILE="{{ backup_root }}/${DATE}.sqlite3"
          sqlite3 {{ db_path }} ".backup '$BACKUP_FILE'"

    - name: Install backup service and timer
      become: true
      copy:
        dest: "/etc/systemd/system/{{ item.name }}"
        content: "{{ item.content }}"
      loop:
        - name: "{{ app_user }}-backup.service"
          content: |
            [Unit]
            Description=Back up {{ app_user }} sqlite db

            [Service]
            Type=oneshot
            User={{ app_user }}
            Group={{ app_group }}
            ExecStart=/usr/local/bin/backup-{{ app_user }}.sh

        - name: "{{ app_user }}-backup.timer"
          content: |
            [Unit]
            Description=Back up {{ app_user }} db

            [Timer]
            OnCalendar=daily

    - name: Enable backup timer
      become: true
      systemd:
        name: "{{ app_user }}-backup.timer"
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: reload caddy
      become: true
      systemd:
        name: caddy.service
        state: reloaded
        daemon_reload: true

    - name: restart splootwyze
      become: true
      systemd:
        name: "{{ app_user }}.service"
        state: restarted
        daemon_reload: true
